service: hubi-api

frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

provider:
  name: aws
  stackName: hubi-api-${opt:stage, 'development'}
  runtime: nodejs14.x
  stage: ${opt:stage, 'development'}
  region: ${opt:region, 'sa-east-1'}
  environment:
    HUB_ID: ${env:HUB_ID}
    FACEIT_API_KEY: ${env:FACEIT_API_KEY}

functions:
  root:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
custom:
  customDomain:
    domainName: hubi.aws.hugo.dev.br
    endpointType: regional
    apiType: http
    createRoute53Record: false
